version: "3.8"

services:
  merchandise-service:
    image: merchandise-service
    hostname: merchandise-service
    ports:
      - "5000:80"
    depends_on: 
      - supply-service
      - emailing-service
      - employees-service
      - stock-api

  supply-service:
    image: ghcr.io/ozon-edu-csharp-2021/supply-service:main
    hostname: supply-service
    ports:
      - "5100:80"

  emailing-service:
    image: ghcr.io/ozon-edu-csharp-2021/emailing-service:main
    hostname: emailing-service
    ports:
      - "5200:80"

  employees-service:
    image: ghcr.io/ozon-edu-csharp-2021/employees-service:main
    hostname: employees-service
    ports:
      - "5300:80"

  stock-api:
    image: ghcr.io/ozon-edu-csharp-2021/stock-api:main
    hostname: stock-api
    ports:
      - "5400:80"