version: "3.8"

services:
  merchandise-service:
    image: merchandise-service:local
    build: ../
    hostname: merchandise-service
    ports:
      - "5000:5000"
      - "5004:5004"
    environment:
      DatabaseConnectionOptions__ConnectionString: "Host=host.docker.internal;Port=5428;Database=merchandise-service;Username=postgres;Password=merchandiseServicePassword"
    depends_on:
      - supply-service
      - emailing-service
      - employees-service
      - stock-api
      - merchandise-service-db

  supply-service:
    image: ghcr.io/ozon-edu-csharp-2021/supply-service:main
    ports:
      - "5100:80"
    environment:
      DbConfiguration__ConnectionString: "Host=host.docker.internal;Port=5426;Database=supply-service;Username=postgres;Password=supplyServicePassword"
    hostname: supply-service
    depends_on:
      - supply-service-db
  
  emailing-service:
    image: ghcr.io/ozon-edu-csharp-2021/emailing-service:main
    hostname: emailing-service
    ports:
      - "5200:80"
    
  employees-service:
    image: ghcr.io/ozon-edu-csharp-2021/employees-service:main
    hostname: employees-service
    ports:
      - "5300:80"
    depends_on:
      - employees-service-db
    volumes:
      - ./src:/src
    
  stock-api:
    image: ghcr.io/ozon-edu-csharp-2021/stock-api:main
    hostname: stock-api
    ports:
      - "5400:80"
    environment:
      DatabaseConnectionOptions__ConnectionString: "Host=host.docker.internal;Port=5427;Database=stock-api;Username=postgres;Password=stockApiPassword"
    depends_on:
      - stock-api-db
      
  employees-service-db:
    image: postgres:latest
    ports:
      - "5425:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: employees-service
    volumes:
      - ./db/employees-service-postgres-db/dbdata:/var/lib/postgresql/data"

  supply-service-db:
    image: postgres:latest
    ports:
      - "5426:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supplyServicePassword
      POSTGRES_DB: supply-service
  
  stock-api-db:
    image: postgres:latest
    ports:
      - "5427:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: stockApiPassword
      POSTGRES_DB: stock-api

  merchandise-service-db:
    image: postgres:latest
    ports:
      - "5428:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: merchandiseServicePassword
      POSTGRES_DB: merchandise-service